### ISSUE TITLE
Testing best practices (especially around doctests)

### ISSUE THREAD

**Issue by marceldegraaf** [niftyn8/elixir_style_guide#91]
I'm pretty new to Elixir and I'm building my first open source package. Obviously I'm aiming for good test coverage, but I'm not sure where to draw the line between using doctests in my modules, and using normal tests in test scripts.

Is there a convention for this? Can/should this be added to the style guide?

**Comment by asaaki** [comment]
For the documented public interface of your library/application you probably want to utilize doctests, so you also know when your documentation and implementation would diverge.

Since you can't or won't cover all your cases in doctests you still want to thoroughly do normal tests anyway. Also for not documented functions, which can still be accessed publicly should be covered, too.

I'm not sure if and how this could and should be codified into a style guide. I guess this is more a general recommendation for testing practices, which doesn't necessarily need to belong to a style guide, does it?

**Comment by marceldegraaf** [comment]
@asaaki thanks for the detailed response. I agree that testing practices don't really belong in a style guide, so I'll close this issue.

**Comment by eksperimental** [comment]
as a suggestion, which does not necessarily need to be included in the style guide, is that when implementing doctest, o not duplicate the same test in your _test.exs file. I have seen that, and If you still want to do that, it is still better to use different values for testing.
